# Generated by Django 3.2.7 on 2021-09-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
    ]
